sudo: required

os: linux
dist: trusty

group: edge

services:
  - docker

env:
  global:
  - REPORT_EXIT_STATUS=1
  - ACCEPT_EULA=Y
  - PHPSQLDIR=/REPO/msphpsql-dev
  - TEST_PHP_SQL_SERVER=sql
  - SQLSRV_DBNAME=msphpsql_sqlsrv
  - PDOSQLSRV_DBNAME=msphpsql_pdosqlsrv  
  - TEST_PHP_SQL_UID=sa
  - TEST_PHP_SQL_PWD=Password123

before_install:
  - docker pull microsoft/mssql-server-linux
 
install:
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password123' -p 1433:1433 --name=$TEST_PHP_SQL_SERVER -d microsoft/mssql-server-linux
  - docker build --build-arg PHPSQLDIR=$PHPSQLDIR -t msphpsql-dev -f Dockerfile-msphpsql .

before_script:
  - sleep 30
  
script: 
  - travis_retry docker run -e TRAVIS_JOB_ID -t -d -w $PHPSQLDIR --name=client --link $TEST_PHP_SQL_SERVER msphpsql-dev
  - docker ps -a
  - docker logs client
  - travis_retry docker exec client python ./test/functional/setup/setup_dbs.py -dbname $SQLSRV_DBNAME
  - travis_retry docker exec client python ./test/functional/setup/setup_dbs.py -dbname $PDOSQLSRV_DBNAME
  - docker exec client cp ./source/shared/msodbcsql.h ./test/functional/setup/
  - travis_retry docker exec client python ./test/functional/setup/build_ksp.py 
  - docker exec client cp ./test/functional/setup/myKSP.so ./test/functional/sqlsrv/
  - docker exec client cp ./test/functional/setup/myKSP.so ./test/functional/pdo_sqlsrv/
  - travis_retry docker exec client python ./test/functional/setup/run_ksp.py -server $TEST_PHP_SQL_SERVER -dbname $SQLSRV_DBNAME -uid $TEST_PHP_SQL_UID -pwd $TEST_PHP_SQL_PWD 
  - travis_retry docker exec client python ./test/functional/setup/run_ksp.py -server $TEST_PHP_SQL_SERVER -dbname $PDOSQLSRV_DBNAME -uid $TEST_PHP_SQL_UID -pwd $TEST_PHP_SQL_PWD 
  - travis_retry docker exec client php ./source/pdo_sqlsrv/run-tests.php ./test/functional/pdo_sqlsrv/*.phpt
  - travis_retry docker exec client php ./source/sqlsrv/run-tests.php ./test/functional/sqlsrv/*.phpt
  - docker exec client bash -c 'for f in ./test/functional/sqlsrv/*.diff; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true'
  - docker exec client bash -c 'for f in ./test/functional/sqlsrv/*.out; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true'
  - docker exec client bash -c 'for f in ./test/functional/pdo_sqlsrv/*.diff; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true' 
  - docker exec client bash -c 'for f in ./test/functional/pdo_sqlsrv/*.out; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true' 
  - docker exec client python ./test/functional/setup/cleanup_dbs.py -dbname $SQLSRV_DBNAME
  - docker exec client python ./test/functional/setup/cleanup_dbs.py -dbname $PDOSQLSRV_DBNAME
  - docker exec client coveralls -e ./source/shared/ --gcov-options '\-lp'
  - docker stats
  - docker stop client
  - docker ps -a



notifications:
  email: false

